SHEET_ID = "1GaHFHbROav38DKvxHivoyCm3UPHIJ_kF6qL_KCCA_s"

TOP_BUYS_SHEET = "TOP_BUYS"
RS_SCORE_SHEET = "RS_SCORE"
NSE_DATA_SHEET = "NSE_DATA"
STRETCH_RANK_SHEET = "STRETCH_RANK"
PORTFOLIO_SHEET = "PORTFOLIO"

MIN_SCORE = 70
TOP_STOCKS = 25
